export default [
  { image: <img src="./assets/partners/partner1.png" alt="" />},
  { image: <img src="./assets/partners/partner2.png" alt="" />},
  { image: <img src="./assets/partners/partner3.png" alt="" />},
  { image: <img src="./assets/partners/partner4.png" alt="" />},
  { image: <img src="./assets/partners/partner5.png" alt="" />},
  { image: <img src="./assets/partners/partner6.png" alt="" />},
  { image: <img src="./assets/partners/partner7.png" alt="" />},
  { image: <img src="./assets/partners/partner8.png" alt="" />},
  { image: <img src="./assets/partners/partner9.png" alt="" />},
  { image: <img src="./assets/partners/partner10.png" alt="" />},
  { image: <img src="./assets/partners/partner11.png" alt="" />},
  { image: <img src="./assets/partners/partner12.png" alt="" />},
  { image: <img src="./assets/partners/partner13.png" alt="" />},
  { image: <img src="./assets/partners/partner14.png" alt="" />},
  { image: <img src="./assets/partners/partner15.png" alt="" />},
  { image: <img src="./assets/partners/partner16.png" alt="" />},
  { image: <img src="./assets/partners/partner17.png" alt="" />},
  { image: <img src="./assets/partners/partner18.png" alt="" />},
];
